### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by jonaz** [stampzilla/stampzilla-go#104]
http://wirepusher.com or slack support?

- [x] Server `destinations`
- [x] Server `senders`
- [ ] Trigger `senders` based on `labels` in `messages` from `rules`
- [x] UI: `destinations`
- [x] UI: `senders`
- [x] UI: `messages` in `rules`
- [x] Implement `LogSender` (writes the message to a file)
- [x] Implement `MailSender`
- [x] Implement `WirePusherSender`
- [x] Implement `PushBulletSender`

**Comment by stamp** [comment]
https://github.com/stampzilla/stampzilla-go/tree/feature/notifications
