### ISSUE TITLE
v2.0.0-rc2 - Failed to install

### ISSUE THREAD

**Issue by stamp** [stampzilla/stampzilla-go#125]
![stamp_2019-02-17_103858](https://user-images.githubusercontent.com/1146381/52919667-17e13900-3305-11e9-8391-5efb3719f562.png)

**Comment by jonaz** [comment]
It did not fail :P if it have failed where would have been test after for example `Failed to install server`

Fix is:
```
-       return fmt.Errorf("Failed to install %s", strings.Join(nodes, ","))
+       if len(nodes) > 0 {
+               return fmt.Errorf("Failed to install %s", strings.Join(nodes, ","))
+       }
+       return nil

```

I will fix both that and os.Rename soon
