### ISSUE TITLE
Logic evaluation is triggered a lot

### ISSUE THREAD

**Issue by stamp** [stampzilla/stampzilla-go#163]
https://youtu.be/6ItG1sQ3KzQ

![stamp_2019-02-28_112026](https://user-images.githubusercontent.com/1146381/53559759-258b8f80-3b4b-11e9-93d4-1b7ce0f0899d.png)

**Comment by stamp** [comment]
Could be fixed by 
bc989ee

**Comment by jonaz** [comment]
I dont think its the evaluation that is triggered alot but the "server" rules state update to the frontend.
