### ISSUE TITLE
revisit tibber pricelevel calculation

### ISSUE THREAD

**Issue by jonaz** [stampzilla/stampzilla-go#369]
Now its average 24h. A better solution might be to take low/high for last 24h and then use the difference (high-low) of that instead? Otherwise if price is high for 70% of the day that will impact so "high" is normal :)

**Comment by stamp** [comment]
One solution could be to have a parameter that sets for how long you need power. So if it takes 3 hours to charge the car, it will find the 3 cheapest hours available.

Same with heating, if you know that you need heating for 8h every day, then find the cheapest 8 hours

**Comment by jonaz** [comment]
> One solution could be to have a parameter that sets for how long you need power. So if it takes 3 hours to charge the car, it will find the 3 cheapest hours available.
> 
> Same with heating, if you know that you need heating for 8h every day, then find the cheapest 8 hours

That's already implemented exactly that way. This is about the generic priceLevel (low , normal, high).

**Comment by jonaz** [comment]
The usecase I have for more correct priceLevel is to block heating during expensive hours.

**Comment by jonaz** [comment]
This is the existing feature for carcharge :) https://github.com/stampzilla/stampzilla-go/blob/master/nodes/stampzilla-tibber/config.example.json#L2
